name: Create Manual Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build binary
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -o build/bot-ip-whitelister-linux-amd64

    - name: Create Git tag
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag ${{ inputs.tag }}
        git push origin ${{ inputs.tag }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ inputs.tag }}
        tag_name: ${{ inputs.tag }}
        files: build/bot-ip-whitelister-linux-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
